name: 'Compile TEAL'

# **What it does**: Compiles the smart contracts into TEAL codes.
# **Why we have it**: To make sure all smart contracts compile correctly.
# **Who does it impact**: Saves the artifacts into `src/teal` directory.

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch, parent-child ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: write

jobs:
  compile-TEAL:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        submodules: 'true'

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install -r src/test/requirements.txt

      - name: Setup Algorand sandbox
        run: |
          . src/test/sandbox-scripts/sandbox_setup.sh

      - name: Compile contracts to TEAL code
        run: |
          make compile-teal

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            src/teal
            !src/teal/*.py

      - name: Teardown Algorand sandbox
        if: success() || failure()
        run: |
          . src/test/sandbox-scripts/sandbox_teardown.sh